/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'myan' at '15/01/15 4:26' with Gradle 2.2.1
 *
 * @author myan, @date 15/01/15 4:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
